# Generated by Django 5.1a1 on 2024-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
