# Generated by Django 5.1a1 on 2024-06-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_cart_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
