# Generated by Django 5.1a1 on 2024-06-27 09:35

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_created_at_order_order_date_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default=shop.models.product_default_image, null=True, upload_to=shop.models.product_image, verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
